apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-with-target-ns
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  project: target-ns
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
