apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: target-ns
  namespace: argocd
spec:
  description: Project dengan target ns
  sourceRepos:
    - "*"

  destinations:
    - namespace: "ns-1"
      server: "https://kubernetes.default.svc"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
