apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: coba-project
  namespace: argocd
spec:
  description: Coba bikin project
  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
